FlexiCareManager/Controllers/ProgrammeExercisesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FlexiCareManager.Data;
using FlexiCareManager.Models;

namespace FlexiCareManager.Controllers
{
    [Authorize(Roles = "ADMINISTRATOR")]
    public class ProgrammeExercisesController : BaseController
    {
        private readonly FlexiCareManagerContext _context;

        public ProgrammeExercisesController(FlexiCareManagerContext context)
        {
            _context = context;
        }

        // GET: ProgrammeExercises
        // public async Task<IActionResult> Index()
        // {
        //     var FlexiCareManagerContext = _context.ProgrammeExercise.Include(p => p.Exercise).Include(p => p.Programme);
        //     return View(await FlexiCareManagerContext.ToListAsync());
        // }

        // GET: ProgrammeExercises/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var programmeExercise = await _context.ProgrammeExercise
                .Include(p => p.Exercise)
                .Include(p => p.Programme)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (programmeExercise == null)
            {
                return NotFound();
            }

            return View(programmeExercise);
        }

        // GET: ProgrammeExercises/Create
        public async Task<IActionResult> Create(int id)
        {
            var programme = await _context.Programme.FindAsync(id);
            if (programme == null)
            {
                return NotFound();
            }
            var programmeExercise = new ProgrammeExercise { Programme = programme, ProgrammeId = id};
            ViewData["ExerciseId"] = new SelectList(_context.Exercise, "Id", "Name");
            return View(programmeExercise);
        }

        // POST: ProgrammeExercises/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ExerciseId,ProgrammeId,Day,Notes")] ProgrammeExercise programmeExercise)
        {
            if (ModelState.IsValid)
            {
                var exercise = await _context.Exercise.FindAsync(programmeExercise.ExerciseId);
                if (exercise == null){
                    return BadRequest("");
                }
                var programme = await _context.Programme.FindAsync(programmeExercise.ProgrammeId);
                if (programme == null){
                    return BadRequest("");
                }
                programmeExercise.Programme = programme;
                programmeExercise.Exercise = exercise;
                _context.Add(programmeExercise);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Programmes", new {Id = programmeExercise.ProgrammeId});
            }
            ViewData["ExerciseId"] = new SelectList(_context.Exercise, "Id", "Name", programmeExercise.ExerciseId);
            ViewData["ProgrammeId"] = new SelectList(_context.Programme, "Id", "Name", programmeExercise.ProgrammeId);
            return View(programmeExercise);
        }

        // GET: ProgrammeExercises/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var programmeExercise = await _context.ProgrammeExercise.Include(pe => pe.Programme).FirstOrDefaultAsync(pe => pe.Id == id);
            if (programmeExercise == null)
            {
                return NotFound();
            }
            ViewData["ExerciseId"] = new SelectList(_context.Exercise, "Id", "Name", programmeExercise.ExerciseId);
            return View(programmeExercise);
        }

        // POST: ProgrammeExercises/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ExerciseId,ProgrammeId,Day,Notes")] ProgrammeExercise programmeExercise)
        {
            if (id != programmeExercise.Id)
            {
                return NotFound();
            }
            programmeExercise.Exercise = await _context.Exercise.FindAsync(programmeExercise.ExerciseId) ?? new Exercise();
            programmeExercise.Programme = await _context.Programme.FindAsync(programmeExercise.ProgrammeId) ?? new Programme();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(programmeExercise);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProgrammeExerciseExists(programmeExercise.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details", "Programmes", new {Id = programmeExercise!.ProgrammeId});
            }
            ViewData["ExerciseId"] = new SelectList(_context.Exercise, "Id", "Name", programmeExercise.ExerciseId);
            return View(programmeExercise);
        }

        // GET: ProgrammeExercises/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var programmeExercise = await _context.ProgrammeExercise
                .Include(p => p.Exercise)
                .Include(p => p.Programme)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (programmeExercise == null)
            {
                return NotFound();
            }

            return View(programmeExercise);
        }

        // POST: ProgrammeExercises/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var programmeExercise = await _context.ProgrammeExercise.FindAsync(id);
            if (programmeExercise != null)
            {
                _context.ProgrammeExercise.Remove(programmeExercise);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "Programmes", new {Id = programmeExercise!.ProgrammeId});
        }

        private bool ProgrammeExerciseExists(int id)
        {
            return _context.ProgrammeExercise.Any(e => e.Id == id);
        }
    }
}

FlexiCareManager/Views/ProgrammeExercises/Create.cshtml
@model FlexiCareManager.Models.ProgrammeExercise

@{
    ViewData["Title"] = "Create";
}

<h4>Add Exercise for @Model.Programme.Name</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <input type="hidden" asp-for="ProgrammeId"></input>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ExerciseId" class="control-label"></label>
                <select asp-for="ExerciseId" class ="form-control" asp-items="ViewBag.ExerciseId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Day" class="control-label"></label>
                <input asp-for="Day" class="form-control" />
                <span asp-validation-for="Day" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Notes" class="control-label"></label>
                <input asp-for="Notes" class="form-control" />
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                <a asp-action="Details" asp-controller="Programmes" asp-route-id="@Model.ProgrammeId" class="btn btn-secondary">Back</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FlexiCareManager/Views/ProgrammeExercises/Delete.cshtml
@model FlexiCareManager.Models.ProgrammeExercise

@{
    ViewData["Title"] = "Delete";
}

<div>
    <h4>Are you sure you want to remove this Exercise from the Programme?</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Exercise)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Exercise!.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Programme)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Programme!.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Day)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Day)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Notes)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Details" asp-controller="Programmes" asp-route-id="@Model!.ProgrammeId" class="btn btn-secondary">Back</a>
    </form>
</div>

FlexiCareManager/Views/ProgrammeExercises/Details.cshtml
@model FlexiCareManager.Models.ProgrammeExercise

@{
    ViewData["Title"] = "Details";
}

<h1>@Html.DisplayFor(model => model.Exercise!.Name)</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Programme)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Programme!.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Day)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Day)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Notes)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Details" asp-controller="Programmes" asp-route-id="@Model!.ProgrammeId" class="btn btn-secondary">Back</a>
</div>

FlexiCareManager/Views/ProgrammeExercises/Edit.cshtml
@model FlexiCareManager.Models.ProgrammeExercise

@{
    ViewData["Title"] = "Edit";
}

<h4>Edit Exercise for programme: @Html.DisplayFor(model => model.Programme.Name)</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="ProgrammeId"></input>
            <div class="form-group">
                <label asp-for="ExerciseId" class="control-label"></label>
                <select asp-for="ExerciseId" class="form-control" asp-items="ViewBag.ExerciseId"></select>
                <span asp-validation-for="ExerciseId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Day" class="control-label"></label>
                <input asp-for="Day" class="form-control" />
                <span asp-validation-for="Day" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Notes" class="control-label"></label>
                <input asp-for="Notes" class="form-control" />
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a asp-action="Details" asp-controller="Programmes" asp-route-id="@Model.ProgrammeId" class="btn btn-secondary">Back</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FlexiCareManager/Views/ProgrammeExercises/_Index.cshtml
@model IEnumerable<FlexiCareManager.Models.ProgrammeExercise>

@{
    ViewData["Title"] = "Programme Exercises";
}

<h4>Programmes Exercises</h4>

<p>
    <a asp-action="Create" asp-controller="ProgrammeExercises" asp-route-Id=@ViewData["ProgrammeId"]
        class="btn btn-primary btn-sm">New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Exercise)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Day)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Notes)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a asp-action="Details" class="text-decoration-none" asp-controller="ProgrammeExercises"
                        asp-route-id="@item.Id">@Html.DisplayFor(modelItem => item.Exercise!.Name)</a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Day)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Notes)
                </td>
                <td>
                    <a asp-action="Edit" asp-controller="ProgrammeExercises" asp-route-id="@item.Id"
                        class="btn btn-primary btn-sm">Edit</a>
                    <a asp-action="Delete" asp-controller="ProgrammeExercises" asp-route-id="@item.Id"
                        class="btn btn-secondary btn-sm">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>