FlexiCareManager/Models/ProgrammeTreatment.cs
using System.ComponentModel.DataAnnotations;

namespace FlexiCareManager.Models;

public class ProgrammeTreatment
{
    public int Id { get; set; }
    [Display(Name = "Treatment")]
    public int TreatmentId {get; set;}
    public virtual Treatment Treatment  { get; set; } = new Treatment();
    [Display(Name = "Programme")]
    public int ProgrammeId {get; set;}
    public virtual Programme Programme  { get; set; } = new Programme();
}

FlexiCareManager/Controllers/ProgrammeTreatmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FlexiCareManager.Data;
using FlexiCareManager.Models;

namespace FlexiCareManager.Controllers
{
    [Authorize(Roles = "ADMINISTRATOR")]
    public class ProgrammeTreatmentsController : BaseController
    {
        private readonly FlexiCareManagerContext _context;

        public ProgrammeTreatmentsController(FlexiCareManagerContext context)
        {
            _context = context;
        }

        // // GET: ProgrammeTreatments
        // public async Task<IActionResult> Index()
        // {
        //     var FlexiCareManagerContext = _context.ProgrammeTreatment.Include(p => p.Programme).Include(p => p.Treatment);
        //     return View(await FlexiCareManagerContext.ToListAsync());
        // }

        // // GET: ProgrammeTreatments/Details/5
        // public async Task<IActionResult> Details(int? id)
        // {
        //     if (id == null)
        //     {
        //         return NotFound();
        //     }

        //     var programmeTreatment = await _context.ProgrammeTreatment
        //         .Include(p => p.Programme)
        //         .Include(p => p.Treatment)
        //         .FirstOrDefaultAsync(m => m.Id == id);
        //     if (programmeTreatment == null)
        //     {
        //         return NotFound();
        //     }

        //     return View(programmeTreatment);
        // }

        // GET: ProgrammeTreatments/Create
        public IActionResult Create(int Id)
        {
            var programme = _context.Programme.FirstOrDefault(p => p.Id == Id);
            if (programme == null){
                return NotFound();
            }
            var programmeTreatment = new ProgrammeTreatment {Programme = programme, ProgrammeId = programme.Id};
            ViewData["TreatmentId"] = new SelectList(_context.Set<Treatment>(), "Id", "Name");
            return View(programmeTreatment);
        }

        // POST: ProgrammeTreatments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,TreatmentId,ProgrammeId")] ProgrammeTreatment programmeTreatment)
        {
            programmeTreatment.Id = 0;
            if (ModelState.IsValid)
            {
                var programme = _context.Programme.FirstOrDefault(p => p.Id == programmeTreatment.ProgrammeId);
                if (programme == null){ return BadRequest(""); }
                var treatment = _context.Treatment.FirstOrDefault(t => t.Id == programmeTreatment.TreatmentId);
                if (treatment == null){ return BadRequest(""); }
                programmeTreatment.Programme = programme;
                programmeTreatment.Treatment = treatment;
                _context.Add(programmeTreatment);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Programmes", new {Id = programmeTreatment.ProgrammeId});
            }
            ViewData["ProgrammeId"] = new SelectList(_context.Programme, "Id", "Id", programmeTreatment.ProgrammeId);
            ViewData["TreatmentId"] = new SelectList(_context.Set<Treatment>(), "Id", "Id", programmeTreatment.TreatmentId);
            return View(programmeTreatment);
        }

        // // GET: ProgrammeTreatments/Edit/5
        // public async Task<IActionResult> Edit(int? id)
        // {
        //     if (id == null)
        //     {
        //         return NotFound();
        //     }

        //     var programmeTreatment = await _context.ProgrammeTreatment.FindAsync(id);
        //     if (programmeTreatment == null)
        //     {
        //         return NotFound();
        //     }
        //     ViewData["ProgrammeId"] = new SelectList(_context.Programme, "Id", "Id", programmeTreatment.ProgrammeId);
        //     ViewData["TreatmentId"] = new SelectList(_context.Set<Treatment>(), "Id", "Id", programmeTreatment.TreatmentId);
        //     return View(programmeTreatment);
        // }

        // // POST: ProgrammeTreatments/Edit/5
        // // To protect from overposting attacks, enable the specific properties you want to bind to.
        // // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        // [HttpPost]
        // [ValidateAntiForgeryToken]
        // public async Task<IActionResult> Edit(int id, [Bind("Id,TreatmentId,ProgrammeId")] ProgrammeTreatment programmeTreatment)
        // {
        //     if (id != programmeTreatment.Id)
        //     {
        //         return NotFound();
        //     }

        //     if (ModelState.IsValid)
        //     {
        //         try
        //         {
        //             _context.Update(programmeTreatment);
        //             await _context.SaveChangesAsync();
        //         }
        //         catch (DbUpdateConcurrencyException)
        //         {
        //             if (!ProgrammeTreatmentExists(programmeTreatment.Id))
        //             {
        //                 return NotFound();
        //             }
        //             else
        //             {
        //                 throw;
        //             }
        //         }
        //         return RedirectToAction(nameof(Index));
        //     }
        //     ViewData["ProgrammeId"] = new SelectList(_context.Programme, "Id", "Id", programmeTreatment.ProgrammeId);
        //     ViewData["TreatmentId"] = new SelectList(_context.Set<Treatment>(), "Id", "Id", programmeTreatment.TreatmentId);
        //     return View(programmeTreatment);
        // }

        // GET: ProgrammeTreatments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var programmeTreatment = await _context.ProgrammeTreatment
                .Include(p => p.Programme)
                .Include(p => p.Treatment)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (programmeTreatment == null)
            {
                return NotFound();
            }

            return View(programmeTreatment);
        }

        // POST: ProgrammeTreatments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var programmeTreatment = await _context.ProgrammeTreatment.FindAsync(id);
            if (programmeTreatment == null)
            {
                return BadRequest("");
            }

            _context.ProgrammeTreatment.Remove(programmeTreatment);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "Programmes", new {Id = programmeTreatment.ProgrammeId});
        }

        private bool ProgrammeTreatmentExists(int id)
        {
            return _context.ProgrammeTreatment.Any(e => e.Id == id);
        }
    }
}

FlexiCareManager/Views/ProgrammeTreatments/Create.cshtml
@model FlexiCareManager.Models.ProgrammeTreatment

@{
    ViewData["Title"] = "Create";
}

<h1>Add Treatment for @Html.DisplayFor(model => model.Programme.Name)</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input type="hidden" asp-for="ProgrammeId">
            </div>
            <div class="form-group">
                <label asp-for="TreatmentId" class="control-label"></label>
                <select asp-for="TreatmentId" class="form-control"
                    asp-items="ViewBag.TreatmentId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" /><a asp-action="Details" asp-controller="Programmes" asp-route-id="@Model.ProgrammeId" class="btn btn-secondary">Back</a>
                
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FlexiCareManager/Views/ProgrammeTreatments/Delete.cshtml
@model FlexiCareManager.Models.ProgrammeTreatment

@{
    ViewData["Title"] = "Delete";
}

<h3>Are you sure you want to remove this Treatment from the Programme?</h3>
<div>
    <h4></h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Programme)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Programme.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Treatment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Treatment.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Details" asp-controller="Programmes" asp-route-id="@Model.ProgrammeId" class="btn btn-secondary">Back</a>
    </form>
</div>

FlexiCareManager/Views/ProgrammeTreatments/Details.cshtml
@model FlexiCareManager.Models.ProgrammeTreatment

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ProgrammeTreatment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Treatment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Treatment!.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Programme)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Programme!.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Back</a>
</div>

FlexiCareManager/Views/ProgrammeTreatments/Edit.cshtml
@model FlexiCareManager.Models.ProgrammeTreatment

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Programme Treatment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="TreatmentId" class="control-label"></label>
                <select asp-for="TreatmentId" class="form-control" asp-items="ViewBag.TreatmentId"></select>
                <span asp-validation-for="TreatmentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProgrammeId" class="control-label"></label>
                <select asp-for="ProgrammeId" class="form-control" asp-items="ViewBag.ProgrammeId"></select>
                <span asp-validation-for="ProgrammeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a asp-action="Details" asp-controller="Programmes" asp-route-id="@Model.ProgrammeId" >Back</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FlexiCareManager/Views/ProgrammeTreatments/_Index.cshtml
@model IEnumerable<FlexiCareManager.Models.ProgrammeTreatment>

@{
    ViewData["Title"] = "Programme Treatments";
    var programmeId = @ViewData["ProgrammeId"];
}

<h4>Programmes Treatments</h4>

<p>
    <a asp-action="Create" asp-controller="ProgrammeTreatments" asp-route-Id="@programmeId" class="btn btn-primary btn-sm">New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Treatment)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Treatment!.Name)
            </td>
            <td>
                <a asp-action="Delete" asp-controller="ProgrammeTreatments" asp-route-id="@item.Id" class="btn btn-secondary btn-sm">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>